stopwords_2gram <- miRetrieve::generate_stopwords(
    c("expression level", "down regulated", "significantly increased",
      "expression pattern", "aimed investigate", "expression mir",
      "chain reaction", "expression level", "controls p",
      "anti mir", "significantly decreased", "analysis performed",
      "increased expression", "first time", "increased mir", "non coding",
      "expression levels", "real time", "this study", "levels mir",
      "healthy controls", "luciferase reporter", "levels significantly",
      "protein expression", "polymerase chain", "molecular mechanism",
      "western blotting", "present study", "target mir",
      "time pcr", "up regulated", "study to", "gene expression",
      "that mir", "signaling pathway", "reverse transcription",
      "quantitative real", "target genes", "study aimed", "results that",
      "p 0.05", "overexpression mir", "reporter assay", "results demonstrated",
      "p 0.001", "expression patterns", "role mir", "important role", "inhibition mir",
      "western blot", "level mir", "therapeutic target", "quantitative reverse",
      "qrt pcr", "time polymerase", "analysis that", "found mir", "highly expressed",
      "significant difference", "rt pcr", "target gene", "expression a",
      "expression significantly", "p 0.01", "control subjects", "a potential",
      "in vivo", "in vitro", "down regulation", "up regulation", "roc curve",
      "effect mir", "regulation mir", "hsa mir", "direct target", "effects mir",
      "compared controls", "wild type", "positively correlated", "methods results",
      "ko mice", "conditioned medium", "correlated mir", "significantly correlated",
      "relationship mir", "regression analysis", "multiple linear", "linear regression",
      "gene mir", "wt cells", "ko cells", "de mirs", "mrna stability", "p 0", "h r",
      "treated mice", "moving averages", "pcr results", "as model", "luciferase assay",
      "its target", "a mir", "as mir", "expression profiles", "confidence interval",
      "study population", "p 0.050", "found be", "be with", "cell lines", "cancer cell",
      "adjacent normal", "normal tissues", "tumor tissue", "a tumor", "cancer patients",
      "digital pcr", "sensitivity specificity", "rt qpcr", "reaction rt", "low expression",
      "cell line", "vs tt", "significant association", "meta analysis", "tt or", "cc vs",
      "dominant model", "case control", "pre mir", "transfection mir", "reporter gene",
      "a direct", "mature mir", "an independent", "has mir", "differentially expressed",
      "used detect", "cells mir", "single nucleotide", "significantly lower", "conditioned medium",
      "to investigate", "predicted mir", "decreased mir", "mrna protein", "a key",
      "cell function", "cell dysfunction", "lna antimir", "upregulation mir",
      "decreased mir", "aim this", "p adjusted", "protein levels", "mrna expression",
      "however mechanisms", "study investigated", "reduced mir", "regulated genes",
      "pcr western", "n 10", "n 15", "compared normal", "aberrant expression", "background aims",
      "and or", "results suggest", "pc vs", "one most", "vitro in", "reporter assays",
      "tumor grades", "p 01", "multivariate analysis", "expression hsa", "cells p",
      "an independent", "altered expression", "over expression", "a therapeutic",
      "significantly in", "receiver operating", "operating characteristic", "a direct",
      "signaling pathways", "situ hybridization", "survival p", "regulated genes",
      "decreased expression", "over expression", "first line", "significantly lower",
      "patients high", "paraffin embedded", "significant association", "coding rnas",
      "genetic models", "association mir", "recessive model", "results mir", "odds ratio",
      "case control", "significantly with", "ratio or", "cancer or", "mouse model",
      "early detection", "p 0.0001", "tissues compared", "significantly downregulated",
      "rt qpcr", "knockdown mir", "low expression", "differentially expressed",
      "compared normal", "patients early", "differential expression", "methylation mir",
      "pri mir", "receiver operating", "decreased expression", "control group", "group mir",
      "short term", "", "a significant", "significantly reduced", "expression increased",
      "increased levels"))

usethis::use_data(stopwords_2gram, overwrite = TRUE)
