---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---
```{r setup}
library(knitr)

knitr::opts_knit$set(root.dir = "/Users/Julian/Documents/Jupyter/miRetrieve_pkg_files/")
```

```{r}
library(miRetrieve) # Load miRetrieve
library(magrittr) # Load magrittr for %>% 

# Set working directory with `setwd()` to folder containing 
# PubMed abstracts ("miRNA_atherosclerosis.txt", "miRNA_lungcancer.txt") and
# miRTarBase ("miRTarBase_MTI.xlsx")

# Load abstracts ---------------------------------------------------------------

# MEDLINE file of abstracts matching "atherosclerosis miRNA"
file <- "miRNA_atherosclerosis.txt"

# Load abstracts
df_atherosclerosis <- read_pubmed_medline(file, topic = "Atherosclerosis") %>% 
    # Subset for original articles
    subset_research() %>%
    # Extract miRNA names mentioned at least twice/abstract
    extract_mir_df(threshold = 2)

# `df` summary -----------------------------------------------------------------

# Number of abstracts
length(unique(df_atherosclerosis[["PMID"]]))

# Number of rows
nrow(df_atherosclerosis)

# Top miRNAs in atherosclerosis ------------------------------------------------

# Plot top miRNAs
plot_mir_count(df_atherosclerosis,
               title = "Most frequently mentioned miRNAs in atherosclerosis")

save_plot("top_mirnas_atherosclerosis.pdf", width = 8, height = 6)

# Extract names of top 3 miRNAs
top_3 <- get_mir(df_atherosclerosis, top = 3)
print(top_3)

# Term association of miR-155 in atherosclerosis -------------------------------

# Plot single word terms for miR-155
plot_mir_terms(df_atherosclerosis, "miR-155",
               title = "Top terms for miR-155 in atherosclerosis")

save_plot("top_terms_155_atherosclerosis.pdf", width = 8, height = 6)

# Plot 2-grams for miR-155
plot_mir_terms(df_atherosclerosis, "miR-155", token = "ngrams", n = 2)

save_plot("top_2grams_155_atherosclerosis.pdf", width = 8, height = 6)

# Plot single word terms for miR-21
plot_mir_terms(df_atherosclerosis, "miR-21",
               title = "Top terms for miR-21 in atherosclerosis")

save_plot("top_terms_21_atherosclerosis.pdf", width = 8, height = 6)

# Plot 2-grams for miR-21
plot_mir_terms(df_atherosclerosis, "miR-21", token = "ngrams", n = 2)

save_plot("top_2grams_21_atherosclerosis.pdf", width = 8, height = 6)

# miRNA biomarker in atherosclerosis -------------------------------------------

# Plot biomarker score distribution
plot_score_biomarker(df_atherosclerosis)

# Identify abstracts with miRNAs as biomarkers
df_biomarker_ath <- calculate_score_biomarker(df_atherosclerosis,
                                          threshold = 6,
                                          discard = TRUE)

# Plot top miRNA biomarker
plot_mir_count(df_biomarker_ath,
               top = 5, title = "Top 5 likely biomarker miRNAs in atherosclerosis")

save_plot("top_mirna_biom_atherosclerosis.pdf", width = 8, height = 6)

# miRNA-target interactions in atherosclerosis ---------------------------------

# Path to miRTarBase
target_db <- "miRTarBase_MTI.xlsx"

# Add miRTarBase targets to df
df_targets_ath <- join_targets(df_atherosclerosis,
                           excel_file = target_db,
                           col.pmid.excel = "References (PMID)",
                           col.target.excel = "Target Gene",
                           col.mir.excel = "miRNA",
                           stem_mir_excel = TRUE)

# Display targets of top 3 miRNAs
plot_target_mir_scatter(df_targets_ath,
                        mir = c("miR-155", "miR-21"),
                        title = "Targets of miR-155 and miR-21 in atherosclerosis")

save_plot("targets_155_21_atherosclerosis.pdf", width = 8, height = 6)

# Display top 3 targets
plot_target_mir_scatter(df_targets_ath,
                        col.mir = miRNA_excel,
                        top = 3,
                        filter_for = "target",
                        title = "Top 3 miRNA targets in atherosclerosis")

save_plot("top_3_targets_atherosclerosis.pdf", width = 8, height = 6)

# Load abstracts lung cancer ------------------------------------------------------

# MEDLINE file of abstracts matching "atherosclerosis miRNA"
file_lc <- "miRNA_lungcancer.txt"

# Load abstracts
df_lc <- read_pubmed_medline(file_lc, topic = "Lung cancer") %>% 
    # Subset for original articles
    subset_research() %>%
    # Extract miRNA names mentioned at least twice/abstract
    extract_mir_df(threshold = 2)

# `df_lc` summary --------------------------------------------------------------

# Number of abstracts
length(unique(df_lc[["PMID"]]))

# Number of rows
nrow(df_lc)

# Top miRNAs in lung cancer ----------------------------------------------------

# Plot top miRNAs in lung cancer
plot_mir_count(df_lc,
               title = "Most frequently mentioned miRNAs in lung cancer")

save_plot("top_mirna_lungcancer.pdf", width = 8, height = 6)

# Compare miR-21-term associations in atherosclerosis and lung cancer ----------

# Combine `df_atherosclerosis` und `df_lc`
df_athlc <- combine_df(df_atherosclerosis, df_lc)

# Top unique miRNAs between atherolsclerosis and lung cancer -------------------
compare_mir_count_unique(df_athlc)

save_plot("unique_mir_ath_lungcancer.pdf", width = 8, height = 6)

# Compare terms miR-21 ---------------------------------------------------------

# Compare shared terms, single word
compare_mir_terms(df_athlc, "miR-21",
                  title = "Comparison of miR-21 term association")

save_plot("comparison_21_ath_lungcancer.pdf", width = 8, height = 6)

# Compare shared terms, 2-gram
compare_mir_terms(df_athlc, "miR-21", token = "ngrams", n = 2,
                  title = "Comparison of miR-21 2-gram association")

save_plot("comparison_21_2gram_ath_lungcancer.pdf", width = 8, height = 6)

# Compare shared terms (log2), single word
compare_mir_terms_log2(df_athlc, "miR-21",
                       title = "Comparison of miR-21 term association (log2)")

save_plot("comparison_21_ath_lungcancer_log2.pdf", width = 8, height = 6)

# Compare shared terms (log2), 2-gram
compare_mir_terms_log2(df_athlc, "miR-21", token = "ngrams", n = 2,
                       title = "Comparison of miR-21 term association (log2)")

save_plot("comparison_21_ath_lungcancer_2gram_log2.pdf", width = 8, height = 6)

# Compare unique terms miR-21
compare_mir_terms_unique(df_athlc, "miR-21")

save_plot("unique_21_ath_lungcancer.pdf", width = 8, height = 6)

# Compare terms miR-155 --------------------------------------------------------

# Compare shared terms, single word
compare_mir_terms(df_athlc, "miR-155",
                  title = "Comparison of miR-155 term association")

save_plot("comparison_155_ath_lungcancer.pdf", width = 8, height = 6)

# Compare shared terms, 2-gram
compare_mir_terms(df_athlc, "miR-155", token = "ngrams", n = 2,
                  title = "Comparison of miR-155 2-gram association")

save_plot("comparison_155_2gram_ath_lungcancer.pdf", width = 8, height = 6)

# Compare shared terms (log2), single word
compare_mir_terms_log2(df_athlc, "miR-155",
                       title = "Comparison of miR-155 term association (log2)")

save_plot("comparison_155_ath_lungcancer_log2.pdf", width = 8, height = 6)

# Compare shared terms (log2), 2-gram
compare_mir_terms_log2(df_athlc, "miR-155", token = "ngrams", n = 2,
                       title = "Comparison of miR-155 term association (log2)")

save_plot("comparison_155_ath_lungcancer_2gram_log2.pdf", width = 8, height = 6)

# Compare unique terms miR-155
compare_mir_terms_unique(df_athlc, "miR-155")

save_plot("unique_155_ath_lungcancer.pdf", width = 8, height = 6)

# miRNA biomarker in lung cancer -----------------------------------------------

# Plot biomarker score distribution
plot_score_biomarker(df_lc)

# Identify abstracts with miRNAs as biomarkers
df_biomarker_lc <- calculate_score_biomarker(df_lc,
                                          threshold = 6,
                                          discard = TRUE)

# Plot top miRNA biomarker
plot_mir_count(df_biomarker_lc,
               top = 5, title = "Top 5 likely biomarker miRNAs in lung cancer")

save_plot("top_mirna_biom_lungcancer.pdf", width = 8, height = 6)

# Compare miR-21-target interaction in atherosclerosis and lung cancer ---------

# Join targets
df_targets_athlc <- join_targets(df_athlc,
                           excel_file = target_db,
                           col.pmid.excel = "References (PMID)",
                           col.target.excel = "Target Gene",
                           col.mir.excel = "miRNA",
                           stem_mir_excel = TRUE)

# Display targets
plot_target_mir_scatter(df_targets_athlc, mir = "miR-21", top = 10, alpha = 0.5, height = 0.2,
                        title = "miR-21 targets in atherosclerosis and lung cancer")

save_plot("target_21_ath_lungcancer.pdf", width = 8, height = 6)

plot_target_mir_scatter(df_targets_athlc, mir = "miR-155", top = 10, alpha = 0.5, height = 0.2,
                        title = "miR-155 targets in atherosclerosis and lung cancer")

save_plot("target_155_ath_lungcancer.pdf", width = 8, height = 6)
```

